# Generated by Django 5.0.2 on 2024-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bme280",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="pressure_sealevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bme280",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="pressure_sealevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp180",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="pressure_sealevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bmp280",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dht22",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ds18b20",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpm",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htu21d",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="noise_LA01",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="noise_LA95",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="noise_LA_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="noise_LA_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="noise_LAeq",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laerm",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="N1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="N10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="N25",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nextpm",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms1003",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms3003",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms5003",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms6003",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pms7003",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="durP1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="durP2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="ratioP1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="ratioP2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ppd42ns",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="counts",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="counts_per_minute",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="hv_pulses",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="sample_time_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm19",
            name="tube",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="counts",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="counts_per_minute",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="hv_pulses",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="sample_time_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_sbm20",
            name="tube",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="counts",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="counts_per_minute",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="hv_pulses",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="sample_time_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="radiation_si22g",
            name="tube",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="co2_ppm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scd30",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="durP1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="durP2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="ratioP1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="ratioP2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sds011",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht11",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht15",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht30",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht31",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht35",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sht85",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="N05",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="N1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="N10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="N25",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="N4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="P0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="P1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="P2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="P4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="TS",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="location",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="sensor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sps30",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
